services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources/
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards/
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres     # define credentials
      POSTGRES_PASSWORD: pass # define credentials
      POSTGRES_DB: postgres       # define database
    ports:
      - "5431:5432"                 # Postgres port 