apiVersion: 1

datasources:
- name: postgres
  uid: "c22050d0-159f-4f1b-bcf8-291f0b88612a"
  type: postgres
  access: proxy
  url: 172.17.0.1:5431
  password: pass
  user: postgres
  database: postgres
  basicAuth: false
  isDefault: true
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
     sslmode: disable
  secureJsonData:
    tlsCACert: ""
    tlsClientCert: ""
    tlsClientKey: ""
  version: 1
  editable: true